### PR TITLE
Feat/project tools

### PR DESCRIPTION
**Pull request by Aparaxium**
## Description

Allows the user to include tools used in projects.

The logic adds the tools under the affiliation. If the affiliation is none, it replaces the affiliation.

## Relevant Pull Requests
This contains the pull requests:

[Pull request 14](https://github.com/jskherman/cv.typ/pull/14)
[Pull request 15](https://github.com/jskherman/cv.typ/pull/15)

### CODE REVIEW

**Comment by jskherman** [comment]
Thank you for your contribution, @Aparaxium. I have some thoughts on this PR. I think we could consider including the mention of tools in the bullet points, rather than having a separate line just for tools. This would help save valuable space.

Having a line for "Tools used" also seems specific for tech-oriented resumes (I try to make template as general as possible to apply to also other engineering fields). One can argue that for other engineering fields (or other non-STEM fields) that you could include tools like Aspen HYSYS, Figma, AutoCAD, IBM SPSS, etc. but it's not really the main point to highlight most of the time in a CV or résumé and can be relegated to the bottom section or briefly in the bullet points.

As of now, I don't see enough of a rationale to merge this but thank you for your PR.

**Comment by jskherman** [comment]
Thank you for your contribution, @Aparaxium. I have some thoughts on this PR. I think we could consider including the mention of tools in the bullet points, rather than having a separate line just for tools. This would help save valuable space.

Having a line for "Tools used" also seems specific for tech-oriented resumes (I try to make template as general as possible to apply to also other engineering fields). One can argue that for other engineering fields (or other non-STEM fields) that you could include tools like Aspen HYSYS, Figma, AutoCAD, IBM SPSS, and etc. but it's not really the main point to highlight most of the time in a CV or résumé and can be relegated to the bottom section or the bullet points.

As of now, I don't see enough of a rationale to merge this but thank you for your contribution. Feel free to fork if you would like to create a more specialized template.

**Comment by Aparaxium** [comment]
Hello,

I appreciate the feedback, after considering it, I believe you are correct in that the bullet points should explain the tools used.

I did try to make this as optional as possible. If the tools are omitted they will not be displayed. I understand if this pull request is not needed.

**Comment by Aparaxium** [comment]
Closing because I don't like this implementation and I will be making changes to it.

**Pull request closed without merging**
